spring:
  application:
    name: trobot
  profiles:
    active: local
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/trobot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
tinkoff:
  token:
  sandbox: false
  broker-tax: 0.3
  country-tax: 13
