spring:
  application:
    name: trobot
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/trobot
    username: postgres
    password: postgres
    driver-cl1ass-name: org.postgresql.Driver


